image: 891377255366.dkr.ecr.eu-west-1.amazonaws.com/gitpod_internal:backend-workspace

jetbrains:
  intellij:
    plugins:
      - org.intellij.scala
    prebuilds:
      version: stable

tasks:
  - name:     backend-workspace
    env:
      COMPOSE_PROFILES: default
    before:   ~/scripts/gp_before.sh
    init:     ~/scripts/gp_init.sh
    command:  ~/scripts/gp_command.sh
