name: nameThisService
on:
  workflow_dispatch:

jobs:
  my-name:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: eu-west-1

    steps:
      - name: Git clone service repository
        uses: actions/checkout@v4

      - name: Execute nameThisService.sh script
        run: |
          echo "" | ./nameThisService.sh

      - name: Generate bob-app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GIT_BOB_APP_ID }}
          private-key: ${{ secrets.GIT_BOB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Push service name changes to master branch
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name ${{ secrets.GIT_BOB_APP_USER_NAME }}
          git config --global user.email ${{ secrets.GIT_BOB_APP_USER_EMAIL }}
          git checkout -b nameThisService
          git commit -am 'My name is...'
          git push origin nameThisService
          gh pr create --fill-first 
          gh pr merge --squash --admin --delete-branch

      - name: Trigger backend-repositories sync-repositories GitHub workflow
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh workflow run repositories.yaml --repo hibobio/backend-repositories
